// src/svelte/components/row-menu/row-menu.svelte
<script lang="ts">
	import Icon from "../icon/icon.svelte";
	import { MenuContent, MenuRoot, MenuTrigger } from "../menu";
	import MenuItem from "../menu-item/menu-item.svelte";

	interface RowMenuProps {
		rowId: string;
		onDeleteClick: (rowId: string) => void;
	}

	const { rowId, onDeleteClick }: RowMenuProps = $props();
</script>

<MenuRoot>
	<MenuTrigger class="row-menu-trigger" direction="bottom-right">
		<Icon lucideId="grip-vertical" />
	</MenuTrigger>
	<MenuContent>
		<MenuItem
			name="Delete"
			lucideId="trash"
			onClick={() => onDeleteClick(rowId)}
		/>
	</MenuContent>
</MenuRoot>

<style>
	:global(.row-menu-trigger) {
		border-radius: var(--button-radius);
		padding: 6px;
	}
</style>

// src/react/loom-app/row-options/components/RowMenu/index.tsx
import React from "react";
import Menu from "src/react/shared/menu";
import MenuItem from "src/react/shared/menu-item";

interface Props {
	id: string;
	rowId: string;
	isOpen: boolean;
	top: number;
	left: number;
	onDeleteClick: (id: string) => void;
}
const RowMenu = React.forwardRef<HTMLDivElement, Props>(function RowMenu(
	{ id, rowId, isOpen, top, left, onDeleteClick }: Props,
	ref
) {
	return (
		<Menu id={id} isOpen={isOpen} top={top} left={left} ref={ref}>
			<div className="dataloom-row-menu">
				<MenuItem
					lucideId="trash-2"
					name="Delete"
					onClick={() => onDeleteClick(rowId)}
				/>
			</div>
		</Menu>
	);
});

export default RowMenu;
