// src/components/MenuItem/index.tsx
import Icon from "src/components/Icon";
import Stack from "src/components/Stack";
import { IconType } from "src/services/icon/types";
import Flex from "../Flex";
import Text from "../Text";

import "./styles.css";

interface Props {
	iconType?: IconType;
	ariaLabel?: string;
	name: string;
	value?: string;
	isSelected?: boolean;
	onClick: (e: React.MouseEvent) => void;
}

export default function MenuItem({
	iconType,
	ariaLabel,
	name,
	value,
	onClick,
	isSelected = false,
}: Props) {
	let className = "NLT__menu-item NLT__selectable";
	if (isSelected) className += " NLT__selected";

	return (
		<div className={className} aria-label={ariaLabel} onClick={onClick}>
			<Flex justify="space-between">
				<Stack>
					{iconType !== undefined && <Icon type={iconType} />}
					<Text value={name} />
				</Stack>
				{value !== undefined && <Text variant="faint" value={value} />}
			</Flex>
		</div>
	);
}

// src/svelte/components/menu-item/menu-item.svelte
<script lang="ts">
	import Flex from "../flex/flex.svelte";
	import Icon from "../icon/icon.svelte";
	import Stack from "../stack/stack.svelte";
	import Text from "../text/text.svelte";

	interface MenuItemProps {
		isSelected?: boolean;
		isFocusable?: boolean;
		isDisabled?: boolean;
		lucideId?: string;
		ariaLabel?: string;
		name: string;
		value?: string;
		onClick?: () => void;
	}

	const {
		isSelected = false,
		isFocusable = true,
		isDisabled = false,
		lucideId,
		ariaLabel,
		name,
		value,
		onClick,
	}: MenuItemProps = $props();

	let className = $derived.by(() => {
		let className = "dataloom-menu-item dataloom-selectable";
		if (isSelected) {
			className += " dataloom-selected";
		} else if (isDisabled) {
			className += " dataloom-disabled";
		}

		if (isFocusable) {
			className += " dataloom-focusable";
		}

		return className;
	});

	function handleClick(event: MouseEvent) {
		if (isDisabled) return;
		if (!onClick) return;

		//Stop propagation so the the menu doesn't remove the focus class
		event.stopPropagation();
		onClick();
	}

	function handleKeyDown(event: KeyboardEvent) {
		if (isDisabled) return;

		if (event.key === "Enter") {
			//Stop propagation so the the menu doesn't close when pressing enter
			event.stopPropagation();
			onClick?.();
		}
	}
</script>

<div
	class={className}
	tabindex={0}
	role="button"
	aria-label={ariaLabel}
	onclick={handleClick}
	onkeydown={handleKeyDown}
>
	<Flex justify="space-between" align="center">
		<Stack isHorizontal>
			{#if lucideId !== undefined}
				<Icon {lucideId} />
			{/if}
			<Text value={name} />
		</Stack>
		{#if value !== undefined}
			<Text variant="faint" {value} />
		{/if}
	</Flex>
</div>

<style>
	.dataloom-menu-item {
		display: flex;
		align-items: center;
		padding: var(--dataloom-spacing--sm) var(--dataloom-spacing--lg);
		width: 100%;
	}
</style>
