// src/react/table-app/table/index.tsx
import React from "react";

import { TableVirtuoso, VirtuosoHandle, TableComponents } from "react-virtuoso";

import {
	RenderTableBodyRow,
	RenderTableFooterRow,
	RenderTableHeaderRow,
} from "./types";

import TableBodyRow from "./table-body-row";
import TableHeaderCell from "./table-header-cell";
import { css } from "@emotion/react";
import { useCompare } from "src/shared/hooks";
import { getTableBorderColor } from "src/shared/color";

interface Props {
	headerRows: RenderTableHeaderRow[];
	bodyRows: RenderTableBodyRow[];
	footerRows: RenderTableFooterRow[];
}

const tableBorderColor = getTableBorderColor();

export default function Table({ headerRows, bodyRows, footerRows }: Props) {
	const tableRef = React.useRef<VirtuosoHandle>(null);

	const didRowsChange = useCompare(bodyRows.length);

	/**
	 * Scrolls to the bottom of the page when the "New Row" button is pressed
	 */
	React.useEffect(() => {
		if (didRowsChange) tableRef.current?.scrollToIndex(bodyRows.length - 1);
		tableRef.current?.scrollTo;
	}, [didRowsChange, bodyRows.length]);

	return (
		<TableVirtuoso
			ref={tableRef}
			overscan={10}
			style={{
				width: "100%",
				height: "100%",
			}}
			totalCount={bodyRows.length}
			components={Components}
			fixedHeaderContent={() =>
				headerRows.map((row) => {
					const { id: rowId, cells } = row;
					return (
						<tr key={rowId}>
							{cells.map((cell, i) => {
								const { id: cellId, columnId, content } = cell;
								return (
									<TableHeaderCell
										key={cellId}
										columnId={columnId}
										content={content}
										isDraggable={i < cells.length - 1}
									/>
								);
							})}
						</tr>
					);
				})
			}
			fixedFooterContent={() =>
				footerRows.map((row) => (
					<tr key={row.id}>
						{row.cells.map((cell) => {
							const { id, content } = cell;
							return <td key={id}>{content}</td>;
						})}
					</tr>
				))
			}
			itemContent={(index) => {
				const row = bodyRows[index];
				const { id: rowId, cells } = row;
				return cells.map((cell, i) => {
					const { id: cellId, content } = cell;
					return (
						<td
							key={cellId}
							data-row-id={
								i === cells.length - 1 ? rowId : undefined
							}
							css={css`
								border-top: 0 !important;
								border-bottom: 1px solid ${tableBorderColor} !important;
								border-left: 1px solid ${tableBorderColor} !important;
								border-right: 0 !important;
								padding: 0 !important;
								overflow: visible;
								vertical-align: top;
								/** 
								* This is a hack to make the children have something to calculate their height percentage from.
								* i.e. if you have a child with height: 100%, it will be 100% of the height of the td, only
								* if the td has a set height value.
								* This doesn't represent the actual height of the td, as that is set by HTML
								*/
								height: 1px;

								&:first-of-type {
									border-left: 0 !important;
								}

								&:last-child {
									border-bottom: 0 !important;
								}
							`}
						>
							{content}
						</td>
					);
				});
			}}
		/>
	);
}

const Components: TableComponents = {
	Table: ({ style, ...props }) => {
		return (
			<table
				css={css`
					table-layout: fixed;
					border-collapse: separate;
				`}
				{...props}
				style={style}
			/>
		);
	},
	TableRow: ({ style, ...props }) => {
		return <TableBodyRow {...props} />;
	},
	TableBody: React.forwardRef(({ style, ...props }, ref) => (
		<tbody {...props} ref={ref} />
	)),
	TableFoot: React.forwardRef(({ style, ...props }, ref) => (
		<tfoot
			css={css`
				position: sticky;
				bottom: 0;
				background-color: var(--background-primary);
				& > tr:first-of-type > td {
					border-bottom: 1px solid ${tableBorderColor} !important;
				}
				& > tr:first-of-type > td:last-child {
					border-left: 1px solid ${tableBorderColor} !important;
					border-bottom: 0 !important;
				}
			`}
			{...props}
			ref={ref}
		/>
	)),
};

// src/svelte/components/table/table.svelte
<script lang="ts">
	import type { ParsedTableData } from "../../utils";
	import CalculationCell from "./calculation-cell.svelte";

	interface TableProps {
		mode: "reading" | "editing";
		data: ParsedTableData;
	}

	const { mode, data }: TableProps = $props();

	let numColumns = $derived(
		data.head.length > 0 ? data.head.length : data.body[0].length,
	);
</script>

{#if mode === "reading"}
	<table>
		{#if data.head.length > 0}
			<thead>
				<tr>
					{#each data.head as header}
						<th>
							{header}
						</th>
					{/each}
				</tr>
			</thead>
		{/if}
		<tbody>
			{#each data.body as row}
				<tr>
					{#each row as cell}
						<td class="dataloom-cell">
							{cell}
						</td>
					{/each}
				</tr>
			{/each}
			<tr>
				{#each Array.from({ length: numColumns })}
					<CalculationCell {mode} />
				{/each}
			</tr>
		</tbody>
	</table>
{:else}
	<table>
		{#if data.head.length > 0}
			<thead>
				<tr>
					{#each data.head as header}
						<th>
							<div class="table-cell-wrapper">
								{header}
							</div>
						</th>
					{/each}
				</tr>
			</thead>
		{/if}
		<tbody>
			{#each data.body as row}
				<tr>
					{#each row as cell}
						<td class="dataloom-cell">
							<div class="table-cell-wrapper">
								{cell}
							</div>
						</td>
					{/each}
				</tr>
			{/each}
			<tr>
				{#each Array.from({ length: numColumns })}
					<CalculationCell {mode} />
				{/each}
			</tr>
		</tbody>
	</table>
{/if}

<!-- <style>
	.dataloom-table {
		display: table;
		table-layout: fixed;
		border-collapse: separate;
	}

	.dataloom-header {
		display: table-header-group;
	}

	.dataloom-body {
		display: table-row-group;
	}

	.dataloom-footer {
		display: table-footer-group;
	}

	.dataloom-row {
		display: table-row;
	}

	.dataloom-cell {
		display: table-cell;
	}

	.dataloom-cell--left-corner {
		width: 35px;
	}

	.dataloom-cell.dataloom-cell--freeze {
		position: sticky;
		left: 0;
		z-index: 2;
		background-color: var(--background-primary);
	}

	.dataloom-cell.dataloom-cell--freeze-header {
		background-color: var(--background-secondary);
		z-index: 3;
	}

	.dataloom-cell.dataloom-cell--freeze-footer {
		z-index: 3;
	}

	.dataloom-cell--header {
		position: sticky;
		top: 0;
		z-index: 1;
		background-color: var(--background-secondary);
		border-bottom: 1px solid var(--table-border-color);
		border-right: 1px solid var(--table-border-color);

		&:last-of-type {
			border-right: 0;
			background-color: var(--background-primary);
		}
	}

	.dataloom-cell--body {
		border-bottom: 1px solid var(--table-border-color);
		border-right: 1px solid var(--table-border-color);
		vertical-align: top;

		/** This is hack to make the children to have something to calculate their height percentage from. */
		height: 1px;

		&:last-of-type {
			border-right: 0;
		}
	}

	.dataloom-cell--footer {
		position: sticky;
		bottom: 0;
		z-index: 1;
		background-color: var(--background-primary);
		border-top: 1px solid var(--table-border-color);
	}

	.dataloom-body > .dataloom-row:last-child > .dataloom-cell {
		border-bottom: 0;
	}
</style> -->

<style>
</style>
