// src/react/loom-app/footer-cell-container/calculation-menu.tsx
import Menu from "src/react/shared/menu";
import MenuItem from "src/react/shared/menu-item";
import type { LoomMenuPosition } from "src/react/shared/menu/types";
import {
	getAriaLabelForCalculation,
	getAriaLabelForNumberCalculation,
	getDisplayNameForCalculation,
	getDisplayNameForNumberCalculation,
} from "src/shared/loom-state/type-display-names";
import {
	CellType,
	GeneralCalculation,
	NumberCalculation,
	type CalculationType,
} from "src/shared/loom-state/types/loom-state";

interface Props {
	id: string;
	value: CalculationType;
	cellType: CellType;
	isOpen: boolean;
	position: LoomMenuPosition;
	onClick: (value: CalculationType) => void;
}
export default function CalculationMenu({
	id,
	value,
	cellType,
	isOpen,
	position,
	onClick,
}: Props) {
	return (
		<Menu id={id} isOpen={isOpen} position={position}>
			<div className="dataloom-function-menu">
				{Object.values(GeneralCalculation).map((type) => (
					<MenuItem
						key={type}
						name={getDisplayNameForCalculation(type)}
						ariaLabel={getAriaLabelForCalculation(type)}
						isSelected={type === value}
						onClick={() => onClick(type)}
					/>
				))}
				{cellType === CellType.NUMBER &&
					Object.values(NumberCalculation).map((type) => (
						<MenuItem
							key={type}
							ariaLabel={getAriaLabelForNumberCalculation(type)}
							name={getDisplayNameForNumberCalculation(type)}
							onClick={() => onClick(type)}
							isSelected={type === value}
						/>
					))}
			</div>
		</Menu>
	);
}

// src/svelte/components/calculation-menu/calculation-menu.svelte
<script lang="ts">
	import {
		getAriaLabelForCalculation,
		getDisplayNameForCalculation,
	} from "src/shared/loom-state/type-display-names";
	import { GeneralCalculation } from "src/shared/loom-state/types/loom-state";
	import { MenuContent, MenuRoot, MenuTrigger } from "../menu";
	import MenuItem from "../menu-item/menu-item.svelte";
	import Text from "../text/text.svelte";

	function handleClick(_type: GeneralCalculation) {}
</script>

<MenuRoot>
	<MenuTrigger class="calculation-menu-trigger">
		<Text value="Calculate" variant="faint" />
	</MenuTrigger>
	<MenuContent>
		{#each Object.values(GeneralCalculation) as type}
			<MenuItem
				name={getDisplayNameForCalculation(type)}
				ariaLabel={getAriaLabelForCalculation(type)}
				isSelected={false}
				onClick={() => handleClick(type)}
			/>
		{/each}
	</MenuContent>
</MenuRoot>

<style>
	:global(.calculation-menu-trigger) {
		padding: var(--dataloom-cell-spacing-x) var(--dataloom-cell-spacing-y);
	}
</style>
